### ISSUE TITLE
Free from rp2040-hal dependency

### ISSUE THREAD

**Issue by MathiasKoch** [jannic/rp2040-flash#3]
Hi,

Would it be possible to free this from the rp2040-hal dependency, so we can re-use this awesome work in other HAL's for the RP?

In this case, I would like to use it in `embassy-rp`, but I would rather not introduce the need for rp2040-hal in the dependency tree if possible.

**Comment by jannic** [comment]
It's not so easy because `rp2040-flash` heavily depends on the ROM functions. They are accessed using [`rp2040_hal::rom_data`](https://docs.rs/rp2040-hal/latest/rp2040_hal/rom_data/index.html). As far as I can see, `embassy-rp` doesn't provide those.

If course it would be possible to access those ROM functions directly. But that could easily double the size of `rp2040-flash`.

So I think the best course of action would be to add something like `rp2040_hal::rom_data` to `embassy-rp`. Then it would be viable to make the underlying HAL selectable by a feature flag in `rp2040-flash`.

Alternatively, you could just copy `rp2040-flash` into `embassy-rp`. After all, it's a rather small crate. The main reason I didn't propose integrating it into `rp2040-hal` yet is that I still expect API changes, and I don't want to introduce breaking changes into `rp2040-hal`. As `embassy-rp` isn't even released to [crates.io](https://crates.io/crates/embassy-rp) yet, that's probably not a concern there.

**Comment by MathiasKoch** [comment]
Alright! I did just that, so i will close this issue for now.
